// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Alpha: typeof import('./src/components/ColorPicker/Alpha.vue')['default']
    Checkboard: typeof import('./src/components/ColorPicker/Checkboard.vue')['default']
    CheckboxButton: typeof import('./src/components/CheckboxButton.vue')['default']
    CheckboxButtonGroup: typeof import('./src/components/CheckboxButtonGroup.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/index.vue')['default']
    Contextmenu: typeof import('./src/components/Contextmenu/index.vue')['default']
    EditableInput: typeof import('./src/components/ColorPicker/EditableInput.vue')['default']
    FileInput: typeof import('./src/components/FileInput.vue')['default']
    FormulaContent: typeof import('./src/components/LaTeXEditor/FormulaContent.vue')['default']
    FullscreenSpin: typeof import('./src/components/FullscreenSpin.vue')['default']
    Hue: typeof import('./src/components/ColorPicker/Hue.vue')['default']
    LaTeXEditor: typeof import('./src/components/LaTeXEditor/index.vue')['default']
    MenuContent: typeof import('./src/components/Contextmenu/MenuContent.vue')['default']
    Saturation: typeof import('./src/components/ColorPicker/Saturation.vue')['default']
    SymbolContent: typeof import('./src/components/LaTeXEditor/SymbolContent.vue')['default']
    WritingBoard: typeof import('./src/components/WritingBoard.vue')['default']
  }
}

export { }
